<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>$(TargetFrameworkValue)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <FileVersion>$(ProductVersion)</FileVersion>
        <ApplicationVersion>$(ProductVersion)</ApplicationVersion>
        <Version>$(ProductVersion)</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CodeAnalysisRuleSet>../CodeStyle.ruleset</CodeAnalysisRuleSet>
        <WarningsAsErrors>
            CS0169,
            CS0618,
            CS1502,
            CS1503,
            CS8524,
            CS8600,
            CS8601,
            CS8602,
            CS8603,
            CS8604,
            CS8625,
            CS8629,
            CS8762,
            CA1510,
            CA1851
        </WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asv.Common" Version="$(AsvCommonVersion)" />
        <PackageReference Include="Asv.IO" Version="$(AsvCommonVersion)" />
        <PackageReference Include="Asv.Cfg" Version="$(AsvCommonVersion)" />
        <PackageReference Include="Asv.Gnss" Version="$(AsvGnssVersion)" />
        <PackageReference Include="Asv.Mavlink" Version="$(AsvMavlinkVersion)" />
        <PackageReference Include="Asv.Sdr" Version="$(AsvSdrVersion)" />
        <PackageReference Include="Asv.Sdr.LimeSdr" Version="$(AsvSdrVersion)" />
        <PackageReference Include="Asv.Hal" Version="$(AsvHalVersion)" />
        <PackageReference Include="DotNext.IO" Version="6.2.1" />


        <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(DotNetVersion)" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="$(DotNetVersion)" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="$(DotNetVersion)" />

        <PackageReference Include="R3" Version="1.3.1" />

        <PackageReference Include="Roslynator.Analyzers" Version="$(RoslynAnalyzersVersion)">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="StyleCop.Analyzers" Version="$(StylecopAnalyzersVersion)">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ZLogger" Version="2.5.10" />
        <PackageReference Include="ConsoleAppFramework" Version="5.2.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <ProjectReference Include="..\Asv.Drones.Gbs.Contracts\Asv.Drones.Gbs.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </None>
        <None Update="appsettings.Development.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </None>
        <None Update="appsettings.Production.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </None>
        <None Update="appsettings.Virtual.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </None>
        <None Update="run.sh">
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        </None>
    </ItemGroup>

</Project>
