<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkValue)</TargetFramework>
        
        <FileVersion>$(ProductVersion)</FileVersion>
        <Version>$(ProductVersion)</Version>
        <PackageVersion>$(ProductVersion)</PackageVersion>
        
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <CodeAnalysisRuleSet>../CodeStyle.ruleset</CodeAnalysisRuleSet>
        <WarningsAsErrors>
            CS0169,
            CS0618,
            CS1502,
            CS1503,
            CS8524,
            CS8600,
            CS8601,
            CS8602,
            CS8603,
            CS8604,
            CS8625,
            CS8629,
            CS8762,
            CA1510,
            CA1851
        </WarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>$(SolutionDir)..\..\asv-drones\src\Asv.Drones.Desktop\bin\Debug\$(TargetFramework)\plugins\Asv.Drones.Plugin.Gbs\</OutputPath>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\asv-drones\src\Asv.Drones.Api\Asv.Drones.Api.csproj" />
        <ProjectReference Include="..\Asv.Drones.Gbs.Contracts\Asv.Drones.Gbs.Contracts.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Shell\Pages\Settings\Subpages\" />
    </ItemGroup>
    <ItemGroup>
      <Compile Update="Shell\Pages\Devices\Gbs\GbsDevicePageView.axaml.cs">
        <DependentUpon>GbsDevicePageView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Shell\Pages\Settings\Subpages\SavedCoordinates\Dialogs\AddCoords\AddCoordsRecordDialogView.axaml.cs">
        <DependentUpon>AddCoordsRecordDialogView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="RS.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>RS.resx</DependentUpon>
      </Compile>
      <Compile Update="Shell\Pages\FlightMode\Widgets\Sections\SatelliteCount\GbsSatelliteCountSectionView.axaml.cs">
        <DependentUpon>GbsSatelliteCountSectionView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Roslynator.Analyzers" Version="$(RoslynAnalyzersVersion)">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="StyleCop.Analyzers" Version="$(StylecopAnalyzersVersion)">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
    <ItemGroup>
      <AdditionalFiles Include="Shell\Pages\Settings\Subpages\SavedCoordinates\SettingsSavedCoordsView.axaml" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Update="RS.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>RS.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>
</Project>
