//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Plugin.Gbs {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Drones.Plugin.Gbs.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SettingsSavedCoordsView_Title_Text {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsView_Title_Text", resourceCulture);
            }
        }
        
        public static string SettingsSavedCoordsView_Description_Text {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsView_Description_Text", resourceCulture);
            }
        }
        
        public static string SettingsSavedCoordsViewModel_MenuItem_Add_Header {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_MenuItem_Add_Header", resourceCulture);
            }
        }
        
        public static string SettingsSavedCoordsViewModel_MenuItem_Remove_Header {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_MenuItem_Remove_Header", resourceCulture);
            }
        }
        
        public static string SettingsSavedCoordsViewModel_AddNewItemDialog_Title {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_AddNewItemDialog_Title", resourceCulture);
            }
        }
        
        public static string SettingsSavedCoordsViewModel_AddNewItemDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_AddNewItemDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string SettingsSavedCoordsViewModel_AddNewItemDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_AddNewItemDialog_CloseButtonText", resourceCulture);
            }
        }
        
        public static string SettingsSavedCoordsViewModel_RemoveItemDialog_Title {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_RemoveItemDialog_Title", resourceCulture);
            }
        }
        
        public static string SettingsSavedCoordsViewModel_RemoveItemDialog_Message {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_RemoveItemDialog_Message", resourceCulture);
            }
        }
        
        public static string AddCoordsRecordDialogView_InputField_Name {
            get {
                return ResourceManager.GetString("AddCoordsRecordDialogView_InputField_Name", resourceCulture);
            }
        }
        
        public static string AddCoordsRecordDialogView_InputField_Accuracy {
            get {
                return ResourceManager.GetString("AddCoordsRecordDialogView_InputField_Accuracy", resourceCulture);
            }
        }
        
        public static string SettingsPageExtension_Group_Gbs_Title {
            get {
                return ResourceManager.GetString("SettingsPageExtension_Group_Gbs_Title", resourceCulture);
            }
        }
        
        public static string SettingsPageExtension_Group_Gbs_FixedModeCoords_Title {
            get {
                return ResourceManager.GetString("SettingsPageExtension_Group_Gbs_FixedModeCoords_Title", resourceCulture);
            }
        }
    }
}
