//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Plugin.Gbs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Plugin.Gbs.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string AddCoordsRecordDialogView_InputField_Accuracy {
            get {
                return ResourceManager.GetString("AddCoordsRecordDialogView_InputField_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc.
        /// </summary>
        public static string AddCoordsRecordDialogView_InputField_Accuracy_ShortHeader {
            get {
                return ResourceManager.GetString("AddCoordsRecordDialogView_InputField_Accuracy_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Point.
        /// </summary>
        public static string AddCoordsRecordDialogView_InputField_GeoPoint {
            get {
                return ResourceManager.GetString("AddCoordsRecordDialogView_InputField_GeoPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo.
        /// </summary>
        public static string AddCoordsRecordDialogView_InputField_GeoPoint_ShortHeader {
            get {
                return ResourceManager.GetString("AddCoordsRecordDialogView_InputField_GeoPoint_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddCoordsRecordDialogView_InputField_Name {
            get {
                return ResourceManager.GetString("AddCoordsRecordDialogView_InputField_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddCoordsRecordDialogView_InputField_Name_ShortHeader {
            get {
                return ResourceManager.GetString("AddCoordsRecordDialogView_InputField_Name_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string AutoModeDialogView_Accuracy_Header {
            get {
                return ResourceManager.GetString("AutoModeDialogView_Accuracy_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc.
        /// </summary>
        public static string AutoModeDialogView_Accuracy_ShortHeader {
            get {
                return ResourceManager.GetString("AutoModeDialogView_Accuracy_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        public static string AutoModeDialogView_Observation_Header {
            get {
                return ResourceManager.GetString("AutoModeDialogView_Observation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observ.
        /// </summary>
        public static string AutoModeDialogView_Observation_ShortHeader {
            get {
                return ResourceManager.GetString("AutoModeDialogView_Observation_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_Ok {
            get {
                return ResourceManager.GetString("Common_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string FixedModeDialogView_Accuracy_Header {
            get {
                return ResourceManager.GetString("FixedModeDialogView_Accuracy_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc.
        /// </summary>
        public static string FixedModeDialogView_Accuracy_ShortHeader {
            get {
                return ResourceManager.GetString("FixedModeDialogView_Accuracy_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Point.
        /// </summary>
        public static string FixedModeDialogView_GeoPoint_Header {
            get {
                return ResourceManager.GetString("FixedModeDialogView_GeoPoint_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo.
        /// </summary>
        public static string FixedModeDialogView_GeoPoint_ShortHeader {
            get {
                return ResourceManager.GetString("FixedModeDialogView_GeoPoint_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FixedModeDialogView_NameDialog_Title {
            get {
                return ResourceManager.GetString("FixedModeDialogView_NameDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current values.
        /// </summary>
        public static string FixedModeDialogView_SaveCurrentValues_Header {
            get {
                return ResourceManager.GetString("FixedModeDialogView_SaveCurrentValues_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FixedModeDialogView_SaveCurrentValues_ShortHeader {
            get {
                return ResourceManager.GetString("FixedModeDialogView_SaveCurrentValues_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved coordinates.
        /// </summary>
        public static string FixedModeDialogView_SavedCoordinates_Header {
            get {
                return ResourceManager.GetString("FixedModeDialogView_SavedCoordinates_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string FixedModeDialogView_SavedCoordinates_ShortHeader {
            get {
                return ResourceManager.GetString("FixedModeDialogView_SavedCoordinates_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string GbsAccuracyTelemetry_Header {
            get {
                return ResourceManager.GetString("GbsAccuracyTelemetry_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acc.
        /// </summary>
        public static string GbsAccuracyTelemetry_ShortHeader {
            get {
                return ResourceManager.GetString("GbsAccuracyTelemetry_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start GBS automatic RTK mode.
        /// </summary>
        public static string GbsAutoModeAction_Description {
            get {
                return ResourceManager.GetString("GbsAutoModeAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Mode.
        /// </summary>
        public static string GbsAutoModeAction_Dialog_Title {
            get {
                return ResourceManager.GetString("GbsAutoModeAction_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto.
        /// </summary>
        public static string GbsAutoModeAction_Header {
            get {
                return ResourceManager.GetString("GbsAutoModeAction_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel GBS mode transition.
        /// </summary>
        public static string GbsCancelModeAction_Description {
            get {
                return ResourceManager.GetString("GbsCancelModeAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GbsCancelModeAction_Header {
            get {
                return ResourceManager.GetString("GbsCancelModeAction_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DGPS rate.
        /// </summary>
        public static string GbsDGpsRateTelemetry_Header {
            get {
                return ResourceManager.GetString("GbsDGpsRateTelemetry_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DGPS.
        /// </summary>
        public static string GbsDGpsRateTelemetry_ShortHeader {
            get {
                return ResourceManager.GetString("GbsDGpsRateTelemetry_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start GBS fixed RTK mode.
        /// </summary>
        public static string GbsFixedModeAction_Description {
            get {
                return ResourceManager.GetString("GbsFixedModeAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Mode.
        /// </summary>
        public static string GbsFixedModeAction_Dialog_Title {
            get {
                return ResourceManager.GetString("GbsFixedModeAction_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Fixed.
        /// </summary>
        public static string GbsFixedModeAction_Header {
            get {
                return ResourceManager.GetString("GbsFixedModeAction_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch GBS to idle mode.
        /// </summary>
        public static string GbsIdleModeAction_Description {
            get {
                return ResourceManager.GetString("GbsIdleModeAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable RTK.
        /// </summary>
        public static string GbsIdleModeAction_Header {
            get {
                return ResourceManager.GetString("GbsIdleModeAction_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move map to this GBS.
        /// </summary>
        public static string GbsLocateBaseStationAction_Description {
            get {
                return ResourceManager.GetString("GbsLocateBaseStationAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate GBS.
        /// </summary>
        public static string GbsLocateBaseStationAction_Header {
            get {
                return ResourceManager.GetString("GbsLocateBaseStationAction_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string GbsModeTelemetry_Header {
            get {
                return ResourceManager.GetString("GbsModeTelemetry_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string GbsModeTelemetry_ShortHeader {
            get {
                return ResourceManager.GetString("GbsModeTelemetry_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        public static string GbsObservationTelemetry_Header {
            get {
                return ResourceManager.GetString("GbsObservationTelemetry_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observ.
        /// </summary>
        public static string GbsObservationTelemetry_ShortHeader {
            get {
                return ResourceManager.GetString("GbsObservationTelemetry_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of satellites for each constellation.
        /// </summary>
        public static string GbsSatelliteCountSectionView_ToolTip {
            get {
                return ResourceManager.GetString("GbsSatelliteCountSectionView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Satellites.
        /// </summary>
        public static string GbsVisibleSatellitesTelemetry_Header {
            get {
                return ResourceManager.GetString("GbsVisibleSatellitesTelemetry_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string GbsVisibleSatellitesTelemetry_ShortHeader {
            get {
                return ResourceManager.GetString("GbsVisibleSatellitesTelemetry_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sats.
        /// </summary>
        public static string GbsVisibleSatellitesTelemetry_Units {
            get {
                return ResourceManager.GetString("GbsVisibleSatellitesTelemetry_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SetCoordsNameDialogView_Name_Header {
            get {
                return ResourceManager.GetString("SetCoordsNameDialogView_Name_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SetCoordsNameDialogView_Name_ShortHeader {
            get {
                return ResourceManager.GetString("SetCoordsNameDialogView_Name_ShortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixedMode Coordinates.
        /// </summary>
        public static string SettingsPage_Group_Gbs_FixedModeCoords_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Group_Gbs_FixedModeCoords_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gbs.
        /// </summary>
        public static string SettingsPage_Group_Gbs_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Group_Gbs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section you can view and save new map coordinates for GBS Fixed Mode.
        /// </summary>
        public static string SettingsSavedCoordsView_Description_Text {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsView_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Coordinates.
        /// </summary>
        public static string SettingsSavedCoordsView_Title_Text {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsView_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_AddNewItemDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_AddNewItemDialog_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_AddNewItemDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_AddNewItemDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new map coordinates.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_AddNewItemDialog_Title {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_AddNewItemDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_MenuItem_Add_Header {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_MenuItem_Add_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_MenuItem_Remove_Header {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_MenuItem_Remove_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the map coordinates?.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_RemoveItemDialog_Message {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_RemoveItemDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_RemoveItemDialog_Title {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_RemoveItemDialog_Title", resourceCulture);
            }
        }
    }
}
