//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Plugin.Gbs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Plugin.Gbs.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string AddCoordsRecordDialogView_InputField_Accuracy {
            get {
                return ResourceManager.GetString("AddCoordsRecordDialogView_InputField_Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AddCoordsRecordDialogView_InputField_Name {
            get {
                return ResourceManager.GetString("AddCoordsRecordDialogView_InputField_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixedMode Coordinates.
        /// </summary>
        public static string SettingsPage_Group_Gbs_FixedModeCoords_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Group_Gbs_FixedModeCoords_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gbs.
        /// </summary>
        public static string SettingsPage_Group_Gbs_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Group_Gbs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section you can view and save new map coordinates for GBS Fixed Mode.
        /// </summary>
        public static string SettingsSavedCoordsView_Description_Text {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsView_Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Coordinates.
        /// </summary>
        public static string SettingsSavedCoordsView_Title_Text {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsView_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_AddNewItemDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_AddNewItemDialog_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_AddNewItemDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_AddNewItemDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new map coordinates.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_AddNewItemDialog_Title {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_AddNewItemDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_MenuItem_Add_Header {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_MenuItem_Add_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_MenuItem_Remove_Header {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_MenuItem_Remove_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the map coordinates?.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_RemoveItemDialog_Message {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_RemoveItemDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SettingsSavedCoordsViewModel_RemoveItemDialog_Title {
            get {
                return ResourceManager.GetString("SettingsSavedCoordsViewModel_RemoveItemDialog_Title", resourceCulture);
            }
        }
    }
}
