
// <auto-generated />
using Asv.Mavlink;
using Asv.Mavlink.Common;

// AUTOGENERATED PARAMS 
// Do not edit manually
// This file is generated from JSON files by text temaplate:
// * (board.params.json) :         RSGA common board parameters

namespace Asv.Drones.Gbs.Contracts
{
    public partial class MavParams : IMavParamsSource
    { 
        public static IMavParamsSource Instance { get; } = new MavParams();

        /// <summary>
        /// BRD_SYS_ID (int)
        /// [0-255], default: 1
        /// System ID
        /// 
        /// Units: 
        /// Group: BOARD
        /// Category: System
        /// RebootRequired: false
        /// Volatile: false
        /// Increment: 1
        /// Global index:[0] File index:[0] Source:board.params.json
        /// </summary>
        public static readonly IMavParamTypeMetadata BrdSysId = new MavParamTypeMetadata("BRD_SYS_ID", MavParamType.MavParamTypeInt32)
        {
            Group = "BOARD",
            Category = "System",
            ShortDesc = "System ID",
            LongDesc = "",
            Units = "",
            RebootRequired = false,
            Volatile = false,
            MinValue = (int)0,
            MaxValue = (int)255,
            DefaultValue = (int)1,
            Increment = (int)1,
            Values = [
            ],
            Bitmask = [
            ]
        };
        /// <summary>
        /// BRD_COM_ID (int)
        /// [0-255], default: 254
        /// Component ID
        /// 
        /// Units: 
        /// Group: BOARD
        /// Category: System
        /// RebootRequired: false
        /// Volatile: false
        /// Increment: 1
        /// Global index:[1] File index:[1] Source:board.params.json
        /// </summary>
        public static readonly IMavParamTypeMetadata BrdComId = new MavParamTypeMetadata("BRD_COM_ID", MavParamType.MavParamTypeInt32)
        {
            Group = "BOARD",
            Category = "System",
            ShortDesc = "Component ID",
            LongDesc = "",
            Units = "",
            RebootRequired = false,
            Volatile = false,
            MinValue = (int)0,
            MaxValue = (int)255,
            DefaultValue = (int)254,
            Increment = (int)1,
            Values = [
            ],
            Bitmask = [
            ]
        };
        /// <summary>
        /// BRD_SERIAL_NUM (int)
        /// [0-9999999], default: 13
        /// Serial number 
        /// Serial number of the board, used for identification [format=00000]
        /// Units: 
        /// Group: BOARD
        /// Category: System
        /// RebootRequired: false
        /// Volatile: false
        /// Increment: 1
        /// Global index:[2] File index:[2] Source:board.params.json
        /// </summary>
        public static readonly IMavParamTypeMetadata BrdSerialNum = new MavParamTypeMetadata("BRD_SERIAL_NUM", MavParamType.MavParamTypeInt32)
        {
            Group = "BOARD",
            Category = "System",
            ShortDesc = "Serial number ",
            LongDesc = "Serial number of the board, used for identification [format=00000]",
            Units = "",
            RebootRequired = false,
            Volatile = false,
            MinValue = (int)0,
            MaxValue = (int)9999999,
            DefaultValue = (int)13,
            Increment = (int)1,
            Values = [
            ],
            Bitmask = [
            ]
        };
        /// <summary>
        /// BRD_REBOOT_CMD (int)
        /// [0-1], default: 0
        /// Reboot
        /// Reboot now command [widget=button; icon=restart-alert;]
        /// Units: 
        /// Group: BOARD
        /// Category: System
        /// RebootRequired: false
        /// Volatile: false
        /// Increment: 1
        /// Global index:[3] File index:[3] Source:board.params.json
        /// </summary>
        public static readonly IMavParamTypeMetadata BrdRebootCmd = new MavParamTypeMetadata("BRD_REBOOT_CMD", MavParamType.MavParamTypeInt32)
        {
            Group = "BOARD",
            Category = "System",
            ShortDesc = "Reboot",
            LongDesc = "Reboot now command [widget=button; icon=restart-alert;]",
            Units = "",
            RebootRequired = false,
            Volatile = false,
            MinValue = (int)0,
            MaxValue = (int)1,
            DefaultValue = (int)0,
            Increment = (int)1,
            Values = [
            ],
            Bitmask = [
            ]
        };
        /// <summary>
        /// BRD_SHUTDOWN_CMD (int)
        /// [0-1], default: 0
        /// Shutdown
        /// Shutdown now command [widget=button; icon=power;]
        /// Units: 
        /// Group: BOARD
        /// Category: System
        /// RebootRequired: false
        /// Volatile: false
        /// Increment: 1
        /// Global index:[4] File index:[4] Source:board.params.json
        /// </summary>
        public static readonly IMavParamTypeMetadata BrdShutdownCmd = new MavParamTypeMetadata("BRD_SHUTDOWN_CMD", MavParamType.MavParamTypeInt32)
        {
            Group = "BOARD",
            Category = "System",
            ShortDesc = "Shutdown",
            LongDesc = "Shutdown now command [widget=button; icon=power;]",
            Units = "",
            RebootRequired = false,
            Volatile = false,
            MinValue = (int)0,
            MaxValue = (int)1,
            DefaultValue = (int)0,
            Increment = (int)1,
            Values = [
            ],
            Bitmask = [
            ]
        };
        /// <summary>
        /// BRD_RESTART_CMD (int)
        /// [0-1], default: 0
        /// Restart
        /// Restart service now command [widget=button; icon=restart;]
        /// Units: 
        /// Group: BOARD
        /// Category: System
        /// RebootRequired: false
        /// Volatile: false
        /// Increment: 1
        /// Global index:[5] File index:[5] Source:board.params.json
        /// </summary>
        public static readonly IMavParamTypeMetadata BrdRestartCmd = new MavParamTypeMetadata("BRD_RESTART_CMD", MavParamType.MavParamTypeInt32)
        {
            Group = "BOARD",
            Category = "System",
            ShortDesc = "Restart",
            LongDesc = "Restart service now command [widget=button; icon=restart;]",
            Units = "",
            RebootRequired = false,
            Volatile = false,
            MinValue = (int)0,
            MaxValue = (int)1,
            DefaultValue = (int)0,
            Increment = (int)1,
            Values = [
            ],
            Bitmask = [
            ]
        };
        /// <summary>
        /// BRD_V2EXT_ON (int)
        /// [0-1], default: 1
        /// Wrap mavlink
        /// V2 mavlink packets wrapping enabled [widget=combo-box]
        /// Units: 
        /// Group: BOARD
        /// Category: System
        /// RebootRequired: false
        /// Volatile: false
        /// Increment: 1
        /// Global index:[6] File index:[6] Source:board.params.json
        /// </summary>
        public static readonly IMavParamTypeMetadata BrdV2extOn = new MavParamTypeMetadata("BRD_V2EXT_ON", MavParamType.MavParamTypeInt32)
        {
            Group = "BOARD",
            Category = "System",
            ShortDesc = "Wrap mavlink",
            LongDesc = "V2 mavlink packets wrapping enabled [widget=combo-box]",
            Units = "",
            RebootRequired = false,
            Volatile = false,
            MinValue = (int)0,
            MaxValue = (int)1,
            DefaultValue = (int)1,
            Increment = (int)1,
            Values = [
                new ValueTuple<MavParamValue, string>((int)1, "Enabled"),
                new ValueTuple<MavParamValue, string>((int)0, "Disabled"),
            ],
            Bitmask = [
            ]
        };
        public IEnumerable<IMavParamTypeMetadata> Params
        {
            get
            {
                yield return BrdSysId; // Global index:[0] File index:[0] Source:board.params.json
                yield return BrdComId; // Global index:[1] File index:[1] Source:board.params.json
                yield return BrdSerialNum; // Global index:[2] File index:[2] Source:board.params.json
                yield return BrdRebootCmd; // Global index:[3] File index:[3] Source:board.params.json
                yield return BrdShutdownCmd; // Global index:[4] File index:[4] Source:board.params.json
                yield return BrdRestartCmd; // Global index:[5] File index:[5] Source:board.params.json
                yield return BrdV2extOn; // Global index:[6] File index:[6] Source:board.params.json
            }
        }
    }
     

}


