<Project>
  <PropertyGroup>
    <ProductVersion>2.0.0-dev.0</ProductVersion>
    <AvaloniaVersion>11.3.10</AvaloniaVersion>
    <DotNetVersion>10.0.0</DotNetVersion>
    <TargetFrameworkValue>net10.0</TargetFrameworkValue>
    <AsvCommonVersion>3.4.0-dev.9</AsvCommonVersion>
    <AsvGnssVersion>2.0.3-dev.3</AsvGnssVersion>
    <AsvSdrVersion>1.5.26</AsvSdrVersion>
    <AsvHalVersion>1.0.8-dev.11</AsvHalVersion>
    <AsvMavlinkVersion>4.0.19-dev.8</AsvMavlinkVersion>
  </PropertyGroup>
</Project>
