<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>$(TargetFrameworkValue)</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CodeAnalysisRuleSet>../CodeStyle.ruleset</CodeAnalysisRuleSet>
        <WarningsAsErrors>
            CS0169,
            CS0618,
            CS1502,
            CS1503,
            CS8524,
            CS8600,
            CS8601,
            CS8602,
            CS8603,
            CS8604,
            CS8625,
            CS8629,
            CS8762,
            CA1510,
            CA1851
        </WarningsAsErrors>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Asv.Common" Version="$(AsvCommonVersion)" />
        <PackageReference Include="Asv.IO" Version="$(AsvCommonVersion)" />
        <PackageReference Include="Asv.Cfg" Version="$(AsvCommonVersion)" />
        <PackageReference Include="Asv.Gnss" Version="$(AsvGnssVersion)" />
        <PackageReference Include="Asv.Mavlink" Version="$(AsvMavlinkVersion)" />
        <PackageReference Include="Roslynator.Analyzers" Version="$(RoslynAnalyzersVersion)">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="StyleCop.Analyzers" Version="$(StylecopAnalyzersVersion)">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="T4.Build" Version="0.2.5" />
    </ItemGroup>


    <ItemGroup>
      <None Update="JsonParams\MavParams.tt">
        <Generator>TextTemplatingFileGenerator</Generator>
        <LastGenOutput>MavParams.cs</LastGenOutput>
      </None>
    </ItemGroup>


    <ItemGroup>
      <Compile Update="JsonParams\MavParams.cs">
        <DependentUpon>MavParams.tt</DependentUpon>
      </Compile>
    </ItemGroup>
</Project>
